### ISSUE TITLE
Routing Error when running the tests

### ISSUE THREAD

**Issue by lizbur10** [learn-co-students/rails-github-api-v-000#437]
I've been working on the lab for several days but I have not been able to resolve this error: 
Failure/Error: visit '/auth?code=20'
     ActionController::RoutingError:
       No route matches [GET] "/login/oauth/authorize"
I pulled down the solution code and ran learn on that and got the same error.

**Comment by sjwakeman** [comment]
I am encountering this same error. Any ideas for a solution?

Failures:

  1) authentication displays the username on the page
     Failure/Error: visit '/auth?code=20'
     
     ActionController::RoutingError:
       No route matches [GET] "/login/oauth/authorize"
     # /home/learn/.rvm/gems/ruby-2.6.1/gems/actionpack-5.0.7.2/lib/action_dispatch/middleware/debug_exceptions.rb:53:in `call'
     # /home/learn/.rvm/gems/ruby-2.6.1/gems/actionpack-5.0.7.2/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
     # /home/learn/.rvm/gems/ruby-2.6.1/gems/railties-5.0.7.2/lib/rails/rack/logger.rb:36:in `call_app'
     # /home/learn/.rvm/gems/ruby-2.6.1/gems/railties-5.0.7.2/lib/rails/rack/logger.rb:24:in `block in call'
     # /home/learn/.rvm/gems/ruby-2.6.1/gems/activesupport-5.0.7.2/lib/active_support/tagged_logging.rb:69:in `block in tagged'
     # /home/learn/.rvm/gems/ruby-2.6.1/gems/activesupport-5.0.7.2/lib/active_support/tagged_logging.rb:26:in `tagged'
     # /home/learn/.rvm/gems/ruby-2.6.1/gems/activesupport-5.0.7.2/lib/active_support/tagged_logging.rb:69:in `tagged'
     # /home/learn/.rvm/gems/ruby-2.6.1/gems/railties-5.0.7.2/lib/rails/rack/logger.rb:24:in `call'
     # /home/learn/.rvm/gems/ruby-2.6.1/gems/actionpack-5.0.7.2/lib/action_dispatch/middleware/request_id.rb:24:in `call'
     # /home/learn/.rvm/gems/ruby-2.6.1/gems/rack-2.0.7/lib/rack/method_override.rb:22:in `call'
     # /home/learn/.rvm/gems/ruby-2.6.1/gems/rack-2.0.7/lib/rack/runtime.rb:22:in `call'
     # /home/learn/.rvm/gems/ruby-2.6.1/gems/activesupport-5.0.7.2/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
     # /home/learn/.rvm/gems/ruby-2.6.1/gems/actionpack-5.0.7.2/lib/action_dispatch/middleware/executor.rb:12:in `call'
     # /home/learn/.rvm/gems/ruby-2.6.1/gems/actionpack-5.0.7.2/lib/action_dispatch/middleware/static.rb:136:in `call'
     # /home/learn/.rvm/gems/ruby-2.6.1/gems/rack-2.0.7/lib/rack/sendfile.rb:111:in `call'
     # /home/learn/.rvm/gems/ruby-2.6.1/gems/railties-5.0.7.2/lib/rails/engine.rb:522:in `call'
     # /home/learn/.rvm/gems/ruby-2.6.1/gems/rack-2.0.7/lib/rack/urlmap.rb:68:in `block in call'
     # /home/learn/.rvm/gems/ruby-2.6.1/gems/rack-2.0.7/lib/rack/urlmap.rb:53:in `each'
     # /home/learn/.rvm/gems/ruby-2.6.1/gems/rack-2.0.7/lib/rack/urlmap.rb:53:in `call'
     # /home/learn/.rvm/gems/ruby-2.6.1/gems/rack-test-0.6.3/lib/rack/mock_session.rb:30:in `request'
     # /home/learn/.rvm/gems/ruby-2.6.1/gems/rack-test-0.6.3/lib/rack/test.rb:244:in `process_request'
     # /home/learn/.rvm/gems/ruby-2.6.1/gems/rack-test-0.6.3/lib/rack/test.rb:58:in `get'
     # /home/learn/.rvm/gems/ruby-2.6.1/gems/capybara-3.25.0/lib/capybara/rack_test/browser.rb:65:in `process'
     # /home/learn/.rvm/gems/ruby-2.6.1/gems/capybara-3.25.0/lib/capybara/rack_test/browser.rb:52:in `block in process_and_follow_redirects'
     # /home/learn/.rvm/gems/ruby-2.6.1/gems/capybara-3.25.0/lib/capybara/rack_test/browser.rb:47:in `times'
     # /home/learn/.rvm/gems/ruby-2.6.1/gems/capybara-3.25.0/lib/capybara/rack_test/browser.rb:47:in `process_and_follow_redirects'
     # /home/learn/.rvm/gems/ruby-2.6.1/gems/capybara-3.25.0/lib/capybara/rack_test/browser.rb:23:in `visit'
     # /home/learn/.rvm/gems/ruby-2.6.1/gems/capybara-3.25.0/lib/capybara/rack_test/driver.rb:45:in `visit'
     # /home/learn/.rvm/gems/ruby-2.6.1/gems/capybara-3.25.0/lib/capybara/session.rb:276:in `visit'
     # /home/learn/.rvm/gems/ruby-2.6.1/gems/capybara-3.25.0/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
     # ./spec/features/repos_spec.rb:5:in `block (2 levels) in <top (required)>'
