### ISSUE TITLE
OAuth working flawlessly except tests still erroring out with "WebMock::NetConnectNotAllowedError: "

### ISSUE THREAD

**Issue by AubreyNeimeier** [learn-co-students/rails-github-api-v-000#586]
WebMock::NetConnectNotAllowedError:
       Real HTTP connections are disabled. Unregistered request: POST https://github.com/login/oauth/access_token with body 'client_id=28fcc7a36ee07aac2287&client_secret=092d81855b8b22bfd9d10eb8f41fbeda5a2121f2&code=20' with headers {'Accept'=>'application/json', 'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3', 'Content-Type'=>'application/x-www-form-urlencoded', 'User-Agent'=>'Faraday v0.15.2'}
     
       You can stub this request with the following snippet:
     
       stub_request(:post, "https://github.com/login/oauth/access_token").
         with(
           body: {"client_id"=>"28fcc7a36ee07aac2287", "client_secret"=>"092d81855b8b22bfd9d10eb8f41fbeda5a2121f2", "code"=>"20"},
           headers: {
       	  'Accept'=>'application/json',
       	  'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3',
       	  'Content-Type'=>'application/x-www-form-urlencoded',
       	  'User-Agent'=>'Faraday v0.15.2'
           }).
         to_return(status: 200, body: "", headers: {})
     
       registered request stubs:
     
       stub_request(:post, "https://api.github.com/user/repos").
         with(
           body: {"{\"name\":\"a-new-repo\"}"=>true},
           headers: {
       	  'Authorization'=>'token 1'
           })
       stub_request(:get, "https://api.github.com/user").
         with(
           headers: {
       	  'Authorization'=>'token 1'
           })
       stub_request(:post, "https://github.com/login/oauth/access_token").
         with(
           body: {"client_id"=>"28fcc7a36ee07aac2287", "client_secret"=>nil, "code"=>"20"},
           headers: {
       	  'Accept'=>'application/json'
           })
       stub_request(:get, "https://api.github.com/user/repos").
         with(
           headers: {
       	  'Authorization'=>'token 1'
           })
     
       ============================================================
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/webmock-3.4.2/lib/webmock/http_lib_adapters/net_http.rb:114:in `request'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/faraday-0.15.2/lib/faraday/adapter/net_http.rb:87:in `perform_request'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/faraday-0.15.2/lib/faraday/adapter/net_http.rb:43:in `block in call'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/faraday-0.15.2/lib/faraday/adapter/net_http.rb:92:in `with_net_http_connection'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/faraday-0.15.2/lib/faraday/adapter/net_http.rb:38:in `call'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/faraday-0.15.2/lib/faraday/request/url_encoded.rb:15:in `call'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/faraday-0.15.2/lib/faraday/rack_builder.rb:143:in `build_response'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/faraday-0.15.2/lib/faraday/connection.rb:387:in `run_request'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/faraday-0.15.2/lib/faraday/connection.rb:175:in `post'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/faraday-0.15.2/lib/faraday.rb:103:in `method_missing'
     # ./app/controllers/sessions_controller.rb:13:in `create'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/actionpack-5.0.7/lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/actionpack-5.0.7/lib/abstract_controller/base.rb:188:in `process_action'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/actionpack-5.0.7/lib/action_controller/metal/rendering.rb:30:in `process_action'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/actionpack-5.0.7/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/activesupport-5.0.7/lib/active_support/callbacks.rb:126:in `call'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/activesupport-5.0.7/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/activesupport-5.0.7/lib/active_support/callbacks.rb:455:in `call'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/activesupport-5.0.7/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/activesupport-5.0.7/lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/activesupport-5.0.7/lib/active_support/callbacks.rb:90:in `run_callbacks'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/actionpack-5.0.7/lib/abstract_controller/callbacks.rb:19:in `process_action'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/actionpack-5.0.7/lib/action_controller/metal/rescue.rb:20:in `process_action'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/actionpack-5.0.7/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/activesupport-5.0.7/lib/active_support/notifications.rb:164:in `block in instrument'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/activesupport-5.0.7/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/activesupport-5.0.7/lib/active_support/notifications.rb:164:in `instrument'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/actionpack-5.0.7/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/actionpack-5.0.7/lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/activerecord-5.0.7/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/actionpack-5.0.7/lib/abstract_controller/base.rb:126:in `process'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/actionview-5.0.7/lib/action_view/rendering.rb:30:in `process'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/actionpack-5.0.7/lib/action_controller/metal.rb:190:in `dispatch'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/actionpack-5.0.7/lib/action_controller/metal.rb:262:in `dispatch'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/actionpack-5.0.7/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/actionpack-5.0.7/lib/action_dispatch/routing/route_set.rb:32:in `serve'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/actionpack-5.0.7/lib/action_dispatch/journey/router.rb:39:in `block in serve'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/actionpack-5.0.7/lib/action_dispatch/journey/router.rb:26:in `each'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/actionpack-5.0.7/lib/action_dispatch/journey/router.rb:26:in `serve'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/actionpack-5.0.7/lib/action_dispatch/routing/route_set.rb:727:in `call'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/rack_session_access-0.2.0/lib/rack_session_access/middleware.rb:33:in `call'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/rack-2.0.5/lib/rack/etag.rb:25:in `call'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/rack-2.0.5/lib/rack/conditional_get.rb:25:in `call'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/rack-2.0.5/lib/rack/head.rb:12:in `call'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/rack-2.0.5/lib/rack/session/abstract/id.rb:232:in `context'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/rack-2.0.5/lib/rack/session/abstract/id.rb:226:in `call'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/actionpack-5.0.7/lib/action_dispatch/middleware/cookies.rb:613:in `call'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/actionpack-5.0.7/lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/activesupport-5.0.7/lib/active_support/callbacks.rb:97:in `__run_callbacks__'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/activesupport-5.0.7/lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/activesupport-5.0.7/lib/active_support/callbacks.rb:90:in `run_callbacks'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/actionpack-5.0.7/lib/action_dispatch/middleware/callbacks.rb:36:in `call'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/actionpack-5.0.7/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/actionpack-5.0.7/lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/web-console-2.3.0/lib/web_console/middleware.rb:28:in `block in call'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/web-console-2.3.0/lib/web_console/middleware.rb:18:in `catch'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/web-console-2.3.0/lib/web_console/middleware.rb:18:in `call'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/actionpack-5.0.7/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/railties-5.0.7/lib/rails/rack/logger.rb:36:in `call_app'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/railties-5.0.7/lib/rails/rack/logger.rb:24:in `block in call'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/activesupport-5.0.7/lib/active_support/tagged_logging.rb:69:in `block in tagged'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/activesupport-5.0.7/lib/active_support/tagged_logging.rb:26:in `tagged'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/activesupport-5.0.7/lib/active_support/tagged_logging.rb:69:in `tagged'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/railties-5.0.7/lib/rails/rack/logger.rb:24:in `call'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/actionpack-5.0.7/lib/action_dispatch/middleware/request_id.rb:24:in `call'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/rack-2.0.5/lib/rack/method_override.rb:22:in `call'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/rack-2.0.5/lib/rack/runtime.rb:22:in `call'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/activesupport-5.0.7/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/actionpack-5.0.7/lib/action_dispatch/middleware/executor.rb:12:in `call'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/actionpack-5.0.7/lib/action_dispatch/middleware/static.rb:136:in `call'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/rack-2.0.5/lib/rack/sendfile.rb:111:in `call'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/railties-5.0.7/lib/rails/engine.rb:522:in `call'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/rack-2.0.5/lib/rack/urlmap.rb:68:in `block in call'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/rack-2.0.5/lib/rack/urlmap.rb:53:in `each'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/rack-2.0.5/lib/rack/urlmap.rb:53:in `call'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/rack-test-0.6.3/lib/rack/mock_session.rb:30:in `request'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/rack-test-0.6.3/lib/rack/test.rb:244:in `process_request'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/rack-test-0.6.3/lib/rack/test.rb:58:in `get'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/capybara-3.5.1/lib/capybara/rack_test/browser.rb:75:in `process'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/capybara-3.5.1/lib/capybara/rack_test/browser.rb:42:in `process_and_follow_redirects'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/capybara-3.5.1/lib/capybara/rack_test/browser.rb:23:in `visit'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/capybara-3.5.1/lib/capybara/rack_test/driver.rb:45:in `visit'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/capybara-3.5.1/lib/capybara/session.rb:269:in `visit'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/capybara-3.5.1/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
     # ./spec/features/repos_spec.rb:5:in `block (2 levels) in <top (required)>'

  2) visiting root lists repos
     Failure/Error: resp = Faraday.get("https://api.github.com/user?access_token=#{access_token}")
     
     WebMock::NetConnectNotAllowedError:
       Real HTTP connections are disabled. Unregistered request: GET https://api.github.com/user?access_token=1 with headers {'Accept'=>'*/*', 'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3', 'User-Agent'=>'Faraday v0.15.2'}
     
       You can stub this request with the following snippet:
     
       stub_request(:get, "https://api.github.com/user?access_token=1").
         with(
           headers: {
       	  'Accept'=>'*/*',
       	  'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3',
       	  'User-Agent'=>'Faraday v0.15.2'
           }).
         to_return(status: 200, body: "", headers: {})
     
       registered request stubs:
     
       stub_request(:post, "https://api.github.com/user/repos").
         with(
           body: {"{\"name\":\"a-new-repo\"}"=>true},
           headers: {
       	  'Authorization'=>'token 1'
           })
       stub_request(:get, "https://api.github.com/user").
         with(
           headers: {
       	  'Authorization'=>'token 1'
           })
       stub_request(:post, "https://github.com/login/oauth/access_token").
         with(
           body: {"client_id"=>"28fcc7a36ee07aac2287", "client_secret"=>nil, "code"=>"20"},
           headers: {
       	  'Accept'=>'application/json'
           })
       stub_request(:get, "https://api.github.com/user/repos").
         with(
           headers: {
       	  'Authorization'=>'token 1'
           })
     
       ============================================================
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/webmock-3.4.2/lib/webmock/http_lib_adapters/net_http.rb:114:in `request'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/faraday-0.15.2/lib/faraday/adapter/net_http.rb:85:in `perform_request'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/faraday-0.15.2/lib/faraday/adapter/net_http.rb:43:in `block in call'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/faraday-0.15.2/lib/faraday/adapter/net_http.rb:92:in `with_net_http_connection'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/faraday-0.15.2/lib/faraday/adapter/net_http.rb:38:in `call'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/faraday-0.15.2/lib/faraday/request/url_encoded.rb:15:in `call'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/faraday-0.15.2/lib/faraday/rack_builder.rb:143:in `build_response'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/faraday-0.15.2/lib/faraday/connection.rb:387:in `run_request'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/faraday-0.15.2/lib/faraday/connection.rb:138:in `get'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/faraday-0.15.2/lib/faraday.rb:103:in `method_missing'
     # ./app/controllers/repositories_controller.rb:5:in `index'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/actionpack-5.0.7/lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/actionpack-5.0.7/lib/abstract_controller/base.rb:188:in `process_action'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/actionpack-5.0.7/lib/action_controller/metal/rendering.rb:30:in `process_action'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/actionpack-5.0.7/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/activesupport-5.0.7/lib/active_support/callbacks.rb:126:in `call'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/activesupport-5.0.7/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/activesupport-5.0.7/lib/active_support/callbacks.rb:455:in `call'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/activesupport-5.0.7/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/activesupport-5.0.7/lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/activesupport-5.0.7/lib/active_support/callbacks.rb:90:in `run_callbacks'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/actionpack-5.0.7/lib/abstract_controller/callbacks.rb:19:in `process_action'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/actionpack-5.0.7/lib/action_controller/metal/rescue.rb:20:in `process_action'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/actionpack-5.0.7/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/activesupport-5.0.7/lib/active_support/notifications.rb:164:in `block in instrument'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/activesupport-5.0.7/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/activesupport-5.0.7/lib/active_support/notifications.rb:164:in `instrument'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/actionpack-5.0.7/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/actionpack-5.0.7/lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/activerecord-5.0.7/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/actionpack-5.0.7/lib/abstract_controller/base.rb:126:in `process'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/actionview-5.0.7/lib/action_view/rendering.rb:30:in `process'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/actionpack-5.0.7/lib/action_controller/metal.rb:190:in `dispatch'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/actionpack-5.0.7/lib/action_controller/metal.rb:262:in `dispatch'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/actionpack-5.0.7/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/actionpack-5.0.7/lib/action_dispatch/routing/route_set.rb:32:in `serve'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/actionpack-5.0.7/lib/action_dispatch/journey/router.rb:39:in `block in serve'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/actionpack-5.0.7/lib/action_dispatch/journey/router.rb:26:in `each'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/actionpack-5.0.7/lib/action_dispatch/journey/router.rb:26:in `serve'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/actionpack-5.0.7/lib/action_dispatch/routing/route_set.rb:727:in `call'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/rack_session_access-0.2.0/lib/rack_session_access/middleware.rb:33:in `call'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/rack-2.0.5/lib/rack/etag.rb:25:in `call'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/rack-2.0.5/lib/rack/conditional_get.rb:25:in `call'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/rack-2.0.5/lib/rack/head.rb:12:in `call'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/rack-2.0.5/lib/rack/session/abstract/id.rb:232:in `context'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/rack-2.0.5/lib/rack/session/abstract/id.rb:226:in `call'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/actionpack-5.0.7/lib/action_dispatch/middleware/cookies.rb:613:in `call'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/actionpack-5.0.7/lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/activesupport-5.0.7/lib/active_support/callbacks.rb:97:in `__run_callbacks__'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/activesupport-5.0.7/lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/activesupport-5.0.7/lib/active_support/callbacks.rb:90:in `run_callbacks'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/actionpack-5.0.7/lib/action_dispatch/middleware/callbacks.rb:36:in `call'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/actionpack-5.0.7/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/actionpack-5.0.7/lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/web-console-2.3.0/lib/web_console/middleware.rb:28:in `block in call'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/web-console-2.3.0/lib/web_console/middleware.rb:18:in `catch'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/web-console-2.3.0/lib/web_console/middleware.rb:18:in `call'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/actionpack-5.0.7/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/railties-5.0.7/lib/rails/rack/logger.rb:36:in `call_app'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/railties-5.0.7/lib/rails/rack/logger.rb:24:in `block in call'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/activesupport-5.0.7/lib/active_support/tagged_logging.rb:69:in `block in tagged'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/activesupport-5.0.7/lib/active_support/tagged_logging.rb:26:in `tagged'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/activesupport-5.0.7/lib/active_support/tagged_logging.rb:69:in `tagged'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/railties-5.0.7/lib/rails/rack/logger.rb:24:in `call'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/actionpack-5.0.7/lib/action_dispatch/middleware/request_id.rb:24:in `call'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/rack-2.0.5/lib/rack/method_override.rb:22:in `call'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/rack-2.0.5/lib/rack/runtime.rb:22:in `call'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/activesupport-5.0.7/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/actionpack-5.0.7/lib/action_dispatch/middleware/executor.rb:12:in `call'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/actionpack-5.0.7/lib/action_dispatch/middleware/static.rb:136:in `call'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/rack-2.0.5/lib/rack/sendfile.rb:111:in `call'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/railties-5.0.7/lib/rails/engine.rb:522:in `call'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/rack-2.0.5/lib/rack/urlmap.rb:68:in `block in call'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/rack-2.0.5/lib/rack/urlmap.rb:53:in `each'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/rack-2.0.5/lib/rack/urlmap.rb:53:in `call'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/rack-test-0.6.3/lib/rack/mock_session.rb:30:in `request'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/rack-test-0.6.3/lib/rack/test.rb:244:in `process_request'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/rack-test-0.6.3/lib/rack/test.rb:58:in `get'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/capybara-3.5.1/lib/capybara/rack_test/browser.rb:75:in `process'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/capybara-3.5.1/lib/capybara/rack_test/browser.rb:42:in `process_and_follow_redirects'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/capybara-3.5.1/lib/capybara/rack_test/browser.rb:23:in `visit'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/capybara-3.5.1/lib/capybara/rack_test/driver.rb:45:in `visit'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/capybara-3.5.1/lib/capybara/session.rb:269:in `visit'
     # /home/learn/.rvm/gems/ruby-2.3.6/gems/capybara-3.5.1/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
     # ./spec/features/repos_spec.rb:16:in `block (2 levels) in <top (required)>'

Finished in 0.08959 seconds (files took 2.67 seconds to load)
2 examples, 2 failures

Failed examples:

rspec ./spec/features/repos_spec.rb:4 # authentication displays the username on the page
rspec ./spec/features/repos_spec.rb:15 # visiting root lists repos

**Comment by Naomi-Dennis** [comment]
I'm getting the same issue.

**Comment by Naomi-Dennis** [comment]
The reason for the error is the formatting of the stub request in the .spec_helper. It has to match **exactly** what your project sends to github. Everything from the client_id and secret, to the headers has to match perfectly. 

In the error message you will see something like: 
![image](https://user-images.githubusercontent.com/17726736/59290058-a1ff3580-8c45-11e9-9e53-daa319ad4fcb.png)


There will be a snippet directly underneath it that looks like the following:

![image](https://user-images.githubusercontent.com/17726736/59289806-f0f89b00-8c44-11e9-83a5-a592b046af04.png)


Copy that over the stub_request that is failing in the spec file. 


## Example 

For me, the stub request was on line 19 and it was written like the following: 
![image](https://user-images.githubusercontent.com/17726736/59289742-d3c3cc80-8c44-11e9-90c6-8eedd3c68670.png)

I removed that and copied the suggested stub request in the error message. 

In the end the rspec file looked something like: 
![image](https://user-images.githubusercontent.com/17726736/59290155-e7236780-8c45-11e9-8ec6-231bbd6ce9eb.png)


## Caveats
If you change it to hide the secret and id in the .env file, it will still work.

**Comment by Marie-Burns22** [comment]
I was also getting this error. I think I was able to fix it without changing the spec file. 
Seemed that the problem was in the `Faraday.get` in the repositories controller. My app was working in the browser but failing the tests.  A tech coach helped me redo the syntax and make sure there are multiple arguments.  I think the argument that helped (but I couldn't find in the tutorial, but vaguely remember maybe seeing somewhere) was  `'Accept' => 'application/json'`.

Also, check line 20 of the spec file to make sure there is a CLIENT_ID and CLIENT_SECRET.  Looks like right now the most recent version has 2 CLIENT_IDs and no CLIENT_SECRET.
